### ISSUE TITLE
do not start if db is inaccessible

### ISSUE THREAD

**Issue by bennyz** [PUMATeam/catapult#98]
no point to continue

**Comment by dedifferentiator** [comment]
@bennyz could you provide more details about file(s) where it should be fixed?

**Comment by bennyz** [comment]
> @bennyz could you provide more details about file(s) where it should be fixed?
The check should probably go here[1], if it didn't connect an error should be returned

[1] https://github.com/PUMATeam/catapult/blob/master/internal/database/db.go#L39
